"""update review

Revision ID: 513d0f2b5471
Revises: 5bb509efeda7
Create Date: 2024-06-26 15:35:29.091576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513d0f2b5471'
down_revision = '5bb509efeda7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('reviews', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###